services:
  - type: web
    name: growler-api
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_DEBUG
        value: 0
      - key: APP_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: growler-db
          property: connectionString

databases:
  - name: growler-db
    plan: free
